<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CantonTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->toDateTimeString();

        $cantones = [
            array('codigo' => '0101', 'nombre' => 'CUENCA', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0102', 'nombre' => 'GIRÓN', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0103', 'nombre' => 'GUALACEO', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0104', 'nombre' => 'NABÓN', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0105', 'nombre' => 'PAUTE', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0106', 'nombre' => 'PUCARA', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0107', 'nombre' => 'SAN FERNANDO', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0108', 'nombre' => 'SANTA ISABEL', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0109', 'nombre' => 'SIGSIG', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0110', 'nombre' => 'OÑA', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0111', 'nombre' => 'CHORDELEG', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0112', 'nombre' => 'EL PAN', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0113', 'nombre' => 'SEVILLA DE ORO', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0114', 'nombre' => 'GUACHAPALA', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0115', 'nombre' => 'CAMILO PONCE ENRÍQUEZ', 'provinciaid' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0201', 'nombre' => 'GUARANDA', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0202', 'nombre' => 'CHILLANES', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0203', 'nombre' => 'CHIMBO', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0204', 'nombre' => 'ECHEANDÍA', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0205', 'nombre' => 'SAN MIGUEL', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0206', 'nombre' => 'CALUMA', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0207', 'nombre' => 'LAS NAVES', 'provinciaid' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0301', 'nombre' => 'AZOGUES', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0302', 'nombre' => 'BIBLIÁN', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0303', 'nombre' => 'CAÑAR', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0304', 'nombre' => 'LA TRONCAL', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0305', 'nombre' => 'EL TAMBO', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0306', 'nombre' => 'DÉLEG', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0307', 'nombre' => 'SUSCAL', 'provinciaid' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0401', 'nombre' => 'TULCÁN', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0402', 'nombre' => 'BOLÍVAR', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0403', 'nombre' => 'ESPEJO', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0404', 'nombre' => 'MIRA', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0405', 'nombre' => 'MONTÚFAR', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0406', 'nombre' => 'SAN PEDRO DE HUACA', 'provinciaid' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0501', 'nombre' => 'LATACUNGA', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0502', 'nombre' => 'LA MANÁ', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0503', 'nombre' => 'PANGUA', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0504', 'nombre' => 'PUJILI', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0505', 'nombre' => 'SALCEDO', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0506', 'nombre' => 'SAQUISILÍ', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0507', 'nombre' => 'SIGCHOS', 'provinciaid' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0601', 'nombre' => 'RIOBAMBA', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0602', 'nombre' => 'ALAUSI', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0603', 'nombre' => 'COLTA', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0604', 'nombre' => 'CHAMBO', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0605', 'nombre' => 'CHUNCHI', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0606', 'nombre' => 'GUAMOTE', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0607', 'nombre' => 'GUANO', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0608', 'nombre' => 'PALLATANGA', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0609', 'nombre' => 'PENIPE', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0610', 'nombre' => 'CUMANDÁ', 'provinciaid' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0701', 'nombre' => 'MACHALA', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0702', 'nombre' => 'ARENILLAS', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0703', 'nombre' => 'ATAHUALPA', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0704', 'nombre' => 'BALSAS', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0705', 'nombre' => 'CHILLA', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0706', 'nombre' => 'EL GUABO', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0707', 'nombre' => 'HUAQUILLAS', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0708', 'nombre' => 'MARCABELÍ', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0709', 'nombre' => 'PASAJE', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0710', 'nombre' => 'PIÑAS', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0711', 'nombre' => 'PORTOVELO', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0712', 'nombre' => 'SANTA ROSA', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0713', 'nombre' => 'ZARUMA', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0714', 'nombre' => 'LAS LAJAS', 'provinciaid' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0801', 'nombre' => 'ESMERALDAS', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0802', 'nombre' => 'ELOY ALFARO', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0803', 'nombre' => 'MUISNE', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0804', 'nombre' => 'QUININDÉ', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0805', 'nombre' => 'SAN LORENZO', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0806', 'nombre' => 'ATACAMES', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0807', 'nombre' => 'RIOVERDE', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0808', 'nombre' => 'LA CONCORDIA', 'provinciaid' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0901', 'nombre' => 'GUAYAQUIL', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0902', 'nombre' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0903', 'nombre' => 'BALAO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0904', 'nombre' => 'BALZAR', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0905', 'nombre' => 'COLIMES', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0906', 'nombre' => 'DAULE', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0907', 'nombre' => 'DURÁN', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0908', 'nombre' => 'EL EMPALME', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0909', 'nombre' => 'EL TRIUNFO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0910', 'nombre' => 'MILAGRO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0911', 'nombre' => 'NARANJAL', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0912', 'nombre' => 'NARANJITO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0913', 'nombre' => 'PALESTINA', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0914', 'nombre' => 'PEDRO CARBO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0916', 'nombre' => 'SAMBORONDÓN', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0918', 'nombre' => 'SANTA LUCÍA', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0919', 'nombre' => 'SALITRE (URBINA JADO)', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0920', 'nombre' => 'SAN JACINTO DE YAGUACHI', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0921', 'nombre' => 'PLAYAS', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0922', 'nombre' => 'SIMÓN BOLÍVAR', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0923', 'nombre' => 'CORONEL MARCELINO MARIDUEÑA', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0924', 'nombre' => 'LOMAS DE SARGENTILLO', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0925', 'nombre' => 'NOBOL', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0927', 'nombre' => 'GENERAL ANTONIO ELIZALDE', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '0928', 'nombre' => 'ISIDRO AYORA', 'provinciaid' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1001', 'nombre' => 'IBARRA', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1002', 'nombre' => 'ANTONIO ANTE', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1003', 'nombre' => 'COTACACHI', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1004', 'nombre' => 'OTAVALO', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1005', 'nombre' => 'PIMAMPIRO', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1006', 'nombre' => 'SAN MIGUEL DE URCUQUÍ', 'provinciaid' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1101', 'nombre' => 'LOJA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1102', 'nombre' => 'CALVAS', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1103', 'nombre' => 'CATAMAYO', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1104', 'nombre' => 'CELICA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1105', 'nombre' => 'CHAGUARPAMBA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1106', 'nombre' => 'ESPÍNDOLA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1107', 'nombre' => 'GONZANAMÁ', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1108', 'nombre' => 'MACARÁ', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1109', 'nombre' => 'PALTAS', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1110', 'nombre' => 'PUYANGO', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1111', 'nombre' => 'SARAGURO', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1112', 'nombre' => 'SOZORANGA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1113', 'nombre' => 'ZAPOTILLO', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1114', 'nombre' => 'PINDAL', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1115', 'nombre' => 'QUILANGA', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1116', 'nombre' => 'OLMEDO', 'provinciaid' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1201', 'nombre' => 'BABAHOYO', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1202', 'nombre' => 'BABA', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1203', 'nombre' => 'MONTALVO', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1204', 'nombre' => 'PUEBLOVIEJO', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1205', 'nombre' => 'QUEVEDO', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1206', 'nombre' => 'URDANETA', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1207', 'nombre' => 'VENTANAS', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1208', 'nombre' => 'VÍNCES', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1209', 'nombre' => 'PALENQUE', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1210', 'nombre' => 'BUENA FÉ', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1211', 'nombre' => 'VALENCIA', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1212', 'nombre' => 'MOCACHE', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1213', 'nombre' => 'QUINSALOMA', 'provinciaid' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1301', 'nombre' => 'PORTOVIEJO', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1302', 'nombre' => 'BOLÍVAR', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1303', 'nombre' => 'CHONE', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1304', 'nombre' => 'EL CARMEN', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1305', 'nombre' => 'FLAVIO ALFARO', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1306', 'nombre' => 'JIPIJAPA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1307', 'nombre' => 'JUNÍN', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1308', 'nombre' => 'MANTA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1309', 'nombre' => 'MONTECRISTI', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1310', 'nombre' => 'PAJÁN', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1311', 'nombre' => 'PICHINCHA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1312', 'nombre' => 'ROCAFUERTE', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1313', 'nombre' => 'SANTA ANA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1314', 'nombre' => 'SUCRE', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1315', 'nombre' => 'TOSAGUA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1316', 'nombre' => '24 DE MAYO', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1317', 'nombre' => 'PEDERNALES', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1318', 'nombre' => 'OLMEDO', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1319', 'nombre' => 'PUERTO LÓPEZ', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1320', 'nombre' => 'JAMA', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1321', 'nombre' => 'JARAMIJÓ', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1322', 'nombre' => 'SAN VICENTE', 'provinciaid' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1401', 'nombre' => 'MORONA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1402', 'nombre' => 'GUALAQUIZA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1403', 'nombre' => 'LIMÓN INDANZA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1404', 'nombre' => 'PALORA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1405', 'nombre' => 'SANTIAGO', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1406', 'nombre' => 'SUCÚA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1407', 'nombre' => 'HUAMBOYA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1408', 'nombre' => 'SAN JUAN BOSCO', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1409', 'nombre' => 'TAISHA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1410', 'nombre' => 'LOGROÑO', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1411', 'nombre' => 'PABLO SEXTO', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1412', 'nombre' => 'TIWINTZA', 'provinciaid' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1501', 'nombre' => 'TENA', 'provinciaid' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1503', 'nombre' => 'ARCHIDONA', 'provinciaid' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1504', 'nombre' => 'EL CHACO', 'provinciaid' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1507', 'nombre' => 'QUIJOS', 'provinciaid' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1509', 'nombre' => 'CARLOS JULIO AROSEMENA TOLA', 'provinciaid' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1601', 'nombre' => 'PASTAZA', 'provinciaid' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1602', 'nombre' => 'MERA', 'provinciaid' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1603', 'nombre' => 'SANTA CLARA', 'provinciaid' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1604', 'nombre' => 'ARAJUNO', 'provinciaid' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1701', 'nombre' => 'QUITO', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1702', 'nombre' => 'CAYAMBE', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1703', 'nombre' => 'MEJIA', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1704', 'nombre' => 'PEDRO MONCAYO', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1705', 'nombre' => 'RUMIÑAHUI', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1707', 'nombre' => 'SAN MIGUEL DE LOS BANCOS', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1708', 'nombre' => 'PEDRO VICENTE MALDONADO', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1709', 'nombre' => 'PUERTO QUITO', 'provinciaid' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1801', 'nombre' => 'AMBATO', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1802', 'nombre' => 'BAÑOS DE AGUA SANTA', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1803', 'nombre' => 'CEVALLOS', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1804', 'nombre' => 'MOCHA', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1805', 'nombre' => 'PATATE', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1806', 'nombre' => 'QUERO', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1807', 'nombre' => 'SAN PEDRO DE PELILEO', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1808', 'nombre' => 'SANTIAGO DE PÍLLARO', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1809', 'nombre' => 'TISALEO', 'provinciaid' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1901', 'nombre' => 'ZAMORA', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1902', 'nombre' => 'CHINCHIPE', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1903', 'nombre' => 'NANGARITZA', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1904', 'nombre' => 'YACUAMBI', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1905', 'nombre' => 'YANTZAZA (YANZATZA)', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1906', 'nombre' => 'EL PANGUI', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1907', 'nombre' => 'CENTINELA DEL CÓNDOR', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1908', 'nombre' => 'PALANDA', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '1909', 'nombre' => 'PAQUISHA', 'provinciaid' => '19', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2001', 'nombre' => 'SAN CRISTÓBAL', 'provinciaid' => '20', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2002', 'nombre' => 'ISABELA', 'provinciaid' => '20', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2003', 'nombre' => 'SANTA CRUZ', 'provinciaid' => '20', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2101', 'nombre' => 'LAGO AGRIO', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2102', 'nombre' => 'GONZALO PIZARRO', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2103', 'nombre' => 'PUTUMAYO', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2104', 'nombre' => 'SHUSHUFINDI', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2105', 'nombre' => 'SUCUMBÍOS', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2106', 'nombre' => 'CASCALES', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2107', 'nombre' => 'CUYABENO', 'provinciaid' => '21', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2201', 'nombre' => 'ORELLANA', 'provinciaid' => '22', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2202', 'nombre' => 'AGUARICO', 'provinciaid' => '22', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2203', 'nombre' => 'LA JOYA DE LOS SACHAS', 'provinciaid' => '22', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2204', 'nombre' => 'LORETO', 'provinciaid' => '22', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2301', 'nombre' => 'SANTO DOMINGO', 'provinciaid' => '23', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2401', 'nombre' => 'SANTA ELENA', 'provinciaid' => '24', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2402', 'nombre' => 'LA LIBERTAD', 'provinciaid' => '24', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '2403', 'nombre' => 'SALINAS', 'provinciaid' => '24', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '9001', 'nombre' => 'LAS GOLONDRINAS', 'provinciaid' => '25', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '9003', 'nombre' => 'MANGA DEL CURA', 'provinciaid' => '25', 'created_at' => $now, 'updated_at' => $now),
            array('codigo' => '9004', 'nombre' => 'EL PIEDRERO', 'provinciaid' => '25', 'created_at' => $now, 'updated_at' => $now),
        ];
        DB::table('cantones')->insert($cantones);
    }
}
